Refactored core logic
zemiguel20/RoyalGameOfUr pull request #11
Opened 2024-04-19 13:21 UTC by zemiguel20

Refactored the Board, Spot, Piece: This classes now contain logic of the rules of the game, and represent the state of the game and allow to for external systems to update the state of the board.

Refactored game state controller (aka: gamemode): Now just controls the flow of turns as a kind of relay of signals, instead of directly managing every other system.

Also created a prototype move selector.

2024-04-19 13:29 UTC, zemiguel20 reviewed
Double checked: contains all of the intended changes

2024-04-20 15:17 UTC, Marc313 requested changes
Overall it looks pretty clean, so almost ready to merge. I do think we should at least comment out the gamemode.gd and then also create a new scene for testing hotseat. This is also because when I put the move_selector in a game against the AI, it gave some error messages. Let's discuss this further on Monday.

2024-04-20 15:17 UTC, Marc313 commented on scripts/game/spot.gd
> +func _on_mouse_entered():
This seems unnecessary

2024-04-24 09:00 UTC, Marc313 approved these changes

2024-04-24 09:06 UTC, merged