Core logic
zemiguel20/RoyalGameOfUr pull request #4
Opened 2024-02-29 15:04 UTC by zemiguel20

Added prototype core gameplay functionality with Finkel ruleset and hotseat.

https://github.com/zemiguel20/RoyalGameOfUr/assets/57849620/904d6850-3dad-415e-9c1d-cacc352a3072

2024-02-29 16:43 UTC, Marc313 requested changes
Few minor suggestions we can go over on friday.

2024-02-29 16:43 UTC, Marc313 commented on scripts/game/dice/dice.gd
> +var _die_scene: PackedScene = preload("res://scenes/game/dice/d4.tscn")
This one could be nice to leave as an export var, since different environments could use a different dice prefab.

2024-02-29 16:43 UTC, Marc313 commented on scripts/game/gamemode/gamemode.gd
> +	board.setup(7)
Magic number. I would say let's make it an export var for now, and at some point we can move it into some kind of GameSettings resource

2024-02-29 16:43 UTC, Marc313 commented on scripts/game/spot/piece_area.gd
> +extends Spot
We can delete this as it is not used

2024-02-29 16:43 UTC, Marc313 commented on scripts/game/spot/spot.gd
> +@export var is_rosette: bool = false
Since we already seperated gives_extra_roll from is_rosette, we can also separate the other characteristic of a rosette: the tile being safe. Because a rosette is basically a safe tile that gives an extra roll.

So instead we would have is_safe and gives_extra_roll.

2024-02-29 16:43 UTC, Marc313 commented on scripts/game/board.gd
> +	# If the current spot is either a start spot or an end spot, insert it in the track
This sounds wild, but I think the function might still work exactly the same when we do not append the starting track

This is due to the find function returning -1 when it cannot find the current index, which will only happen in the starting zone. Having -1 as the starting-zone then also works out perfectly with the track and target index.
Example: From starting zone, we throw 3. 
current_index = -1
target_index = -1 + 3 = 2, which is the index of the third tile. Perfect.

Your current version does ofcourse seem to be more reliable and bulletproof so let's keep that, just thought it was interesting haha.

2024-02-29 16:43 UTC, Marc313 commented on scripts/game/spot/piece_area.gd
> +extends Spot
The selection might be a bit unclear, I was specifically talking about the whole piece_area.gd script

2024-02-29 16:44 UTC, Marc313 commented on scripts/game/board.gd
> +	# NOTE Get sequence of spots using slice. Slice start and end indexed are [inclusive, exclusive[ respectively.
(In the comment)

2024-03-04 12:35 UTC, zemiguel20 commented on scripts/game/board.gd
> +	# NOTE Get sequence of spots using slice. Slice start and end indexed are [inclusive, exclusive[ respectively.
The bracket side is supposed to mean exclusive

2024-03-04 12:46 UTC, zemiguel20 commented on scripts/game/dice/dice.gd
> +var _die_scene: PackedScene = preload("res://scenes/game/dice/d4.tscn")
Agreed and fixed

2024-03-04 12:49 UTC, zemiguel20 commented on scripts/game/spot/piece_area.gd
> +extends Spot
Fixed

2024-03-04 13:01 UTC, zemiguel20 commented on scripts/game/spot/spot.gd
> +@export var is_rosette: bool = false
agreed and fixed

2024-03-04 13:13 UTC, Marc313 approved these changes

2024-03-04 13:13 UTC, merged